language: node_js

node_js:
  - 4.2
before_script:
  - npm install -g gulp bower
script:
  - bower i
  - gulp build && gulp alltest
env:
  global:
    - NODE_ENV=ci
    - APP_URL=http://localhost:3000
notifications:
  email: false
